
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBasedSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Notes
{

    public int NoteId { get; set; }

    public string NotesDescription { get; set; }

    public Nullable<bool> TakingNewPatients { get; set; }

    public string price { get; set; }

    public string Waiting_Time { get; set; }

    public Nullable<int> SpecialistId { get; set; }

    public Nullable<bool> IsBooking { get; set; }



    public virtual Specialist Specialist { get; set; }

}

}
