//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBasedSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public string Age { get; set; }
        public string EmailAddress { get; set; }
        public string Pass { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string ResetPasswordCode { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
