//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBasedSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebBaseSystemEntities : DbContext
    {
        public WebBaseSystemEntities()
            : base("name=WebBaseSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SpecialistType> SpecialistTypes { get; set; }
        public virtual DbSet<SpecialistTypeSubMenu> SpecialistTypeSubMenus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WayPoint> WayPoints { get; set; }
        public virtual DbSet<Specialist> Specialists { get; set; }
    }
}
